$solution = {
    name                 : 'BOOSTXLBUCKCONV_Buck_VMC_F2837xS',
    cpuSysClock          : 100000,
	adcMaxRange			 : 3.3,
    pwmSwitchingFreq     : {min : 20, max : 200, default : 100},
    vInSenseMaxDefault  : 13.3,
    vOutSenseMaxDefault : 9.76,
    iLMaxSensedDefault   : 5.5,
    iLTripLevelDefault   : 4.0,
	adcPinIin			 : [{label : 'ADC_A0', pin : 0},
                            {label : 'ADC_A1', pin : 1},
                            {label : 'ADC_A2', pin : 2},
                            {label : 'ADC_A3', pin : 3},
                            {label : 'ADC_A4', pin : 4},
                            {label : 'ADC_A5', pin : 5}],
    adcPinVOUT           : [{label : 'ADC_A0', pin : 0},
                            {label : 'ADC_A1', pin : 1},
                            {label : 'ADC_A2', pin : 2},
                            {label : 'ADC_A3', pin : 3},
                            {label : 'ADC_A4', pin : 4},
                            {label : 'ADC_A5', pin : 5}],
    adcPinVIN            : [{label : 'ADC_B0', pin : 0},
                            {label : 'ADC_B1', pin : 1},
                            {label : 'ADC_B2', pin : 2},
                            {label : 'ADC_B3', pin : 3},
                            {label : 'ADC_B4', pin : 4},
                            {label : 'ADC_B5', pin : 5}],
	COMP_NUM             : [{label : 'COMP1', value : 1},
                            {label : 'COMP2', value : 2},
                            {label : 'COMP3', value : 3},
                            {label : 'COMP4', value : 4},
                            {label : 'COMP5', value : 5}],
	Fsw_Fctrl_Ratio      : [{label : 'Control ISR runs at Fsw', value : 1},
                            {label : 'Control ISR runs at Fsw/2', value : 2},
                            {label : 'Control ISR runs at Fsw/3', value : 3}],
	INCR_BUILD      	 : [{label : 'Open Loop', value : 1},
	                	    {label : 'Closed Voltage Loop', value : 2},
                            {label : 'Closed Loop w/o SFRA', value : 3}],
    adcIL                : [{label : 'ADC_A2/COMP1+', pin : 2, comparator : 1},
                            {label : 'ADC_A4/COMP2',  pin : 4, comparator : 2}],
	adcPinIL_AVG		 :  [{label : 'ADC_A0', pin : 0},
	                         {label : 'ADC_A1', pin : 1},
	                         {label : 'ADC_A2', pin : 2},
	                         {label : 'ADC_A3', pin : 3},
	                         {label : 'ADC_A4', pin : 4},
	                         {label : 'ADC_A5', pin : 5}],
                            
    pwmNo                : [{num : 1, adcTriggerSrc : 5}, {num : 2, adcTriggerSrc : 7}, {num : 3, adcTriggerSrc : 9}, {num : 4, adcTriggerSrc : 11}, {num : 5, adcTriggerSrc : 13}]
};
