#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = devkits.target.Generic{1,0,0
#
main.x28L: package/cfg/main.x28L.mak

clean::
	-$(RM) package/cfg/main.x28L.mak
